name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Gradle cache for faster builds
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      #- run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      #- run: flutter test

      # Build apk.
      - run: flutter build apk --release --split-per-abi

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release.apk
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-armeabi-v7a-release.apk
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
